### ISSUE TITLE
Horse Inventory GUI

### ISSUE THREAD

**Issue by merrygfx** [spektrsoyuz/WynnEdits#1]
Whenever I’m riding my horse and want to check my inventory, I have noticed that the inventory gets all messed up while on the horse. I have removed the pack to check without it, and everything seems fine until I put one of the packs on. I was using the latest versions recently released, and I have included screenshots of what exactly is shown when everything is messed up/normal.

**Dark Theme 1.8 & Runic 1.1**:
![86296850df45023cf5e671b50400b192](https://github.com/user-attachments/assets/7f2d7521-ea39-491b-a720-78990557bb17)
![de8796abfe68ff93a9d2b6fce65f3cb5](https://github.com/user-attachments/assets/2f33868b-fbbb-4a3a-8410-852c270a8a92)

**Wynncraft Pack**:
![ea63e9505adf9b25031554d5599b3a8d](https://github.com/user-attachments/assets/2d21c0d6-0eca-4714-a883-6ba71ea245e2)

**Comment by spektrsoyuz** [comment]
Hi, I have fixed this as of the 1.9 release coming later today (Aug 28).

![image](https://github.com/user-attachments/assets/d1d75309-2554-4dc4-a1e1-ba4f899b6605)
